### ISSUE TITLE
Raspberry

### ISSUE THREAD

**Issue by Folgore796** [marcus-j-davies/node-red-contrib-zwave-dotnet#1]
Hi, sorry but i don't find one passage. I have installed mono, and the node in node-red. But I don't find where is possible to search a COM assigned at Z-wave dongle.

Thank'you very much

**Comment by marcus-j-davies** [comment]
Hi,

For *nix it will usually be /dev/ttyACM0
I have yet to include the ability to list available Serial Ports within the configuration screen

Regards

**Comment by Maximus1** [comment]
> Hi, For *nix it will usually be /dev/ttyACM0 I have yet to include the ability to list available Serial Ports within the configuration screen Regards

for better kompatibility use /dev/serial/by-id/your_usb_stick

**Comment by marcus-j-davies** [comment]
Once I start listing the serial ports that one can simple select, there should be no reason to enter anything manually.
