### ISSUE TITLE
Operation

### ISSUE THREAD

**Issue by Folgore796** [marcus-j-davies/node-red-contrib-zwave-dotnet#2]
Hi, I have configured on zwave network a Fibaro multisensor (https://manuals.fibaro.com/motion-sensor/). I try to read a configuration or battery...etc

The result in the msg.payload is this:

node: 2
class: "NodeOperation"
index: 0
value: "Error"
timestamp: "2020-02-28T13:14:29.061027Z"

There is another command?

Thank's.

**Comment by marcus-j-davies** [comment]
Hi Could you send me the payload you are sending?

**Comment by Folgore796** [comment]
My json on msg.payload (if is correct)

{
    "node": 2,
    "operation": "GetBattery"
}

**Comment by marcus-j-davies** [comment]
Ok,

`GetBattery`, is a funny one, it will only work when the device is 'a wake'.
can you query `GetBattery`, the moment it sends a notification on motion detected?

I have door sensors, that also return Error - but they do return correctly, when the device has woken up, and then do i get a response, when calling GetBattery.

Assuming your connected the USB Adapter ok?

**Comment by Folgore796** [comment]
I have try GetConfiguration [parameter], GetWakeInterval, GetBasic.....Same error.

Ok, I understand the GetBattery.

Yes, on raspberry pi4 i need to USB hub, in pi3 is not necessary (now i tested your node on pi3).

**Comment by marcus-j-davies** [comment]
Try this

```
{
    "node": 2,
    "operation": "GetConfiguration"
    "operation_vars": [0xC]
}
 ```

Config Param from
http://manuals-backend.z-wave.info/make.php?lang=en&sku=FGMS-001&cert=ZC10-18015922

**Comment by Folgore796** [comment]
I receive even error, I have downloaded this configuration. It is equal to your link.


[FGMS-001-EN-T-v2.0.pdf](https://github.com/marcus-j-davies/node-red-contrib-zwave-dotnet/files/4267478/FGMS-001-EN-T-v2.0.pdf)

**Comment by marcus-j-davies** [comment]
Ok,
I think this is due to the sleeping  nature of battery operated devices.
they are asleep, unless they need to transmit data.

are you getting z wave messages - when say motion is detected, or light levels change?
if so - try sending your request at that moment.

**Comment by marcus-j-davies** [comment]
Hi
The manual seems to back up my theory - which is common for battery z wave devices.

#5: Operating the device

**Waking up the Motion Sensor:**
The Motion Sensor needs to be woken up to receive information on new
configurations from the controller, like parameters and associations.
To wake up the sensor manually triple click the B-button located inside the housing

**Comment by Folgore796** [comment]
> are you getting z wave messages - when say motion is detected, or light levels change?
> if so - try sending your request at that moment.

Yes I receive the temperature,light,motion, etc... message

**Comment by marcus-j-davies** [comment]
Keep it awake  `triple click the B-button` and send your configurations then.

Or see if you can do it, within the window its sending an event.
I'm not sure how long it will remain awake for though.
hopefully it will remain awake long enough.

**Comment by Folgore796** [comment]
Sorry, I am in office... I have try now, ok.. The battery response is ok and your command ti get configuration. 

Perfect.

Thank'you very much

**Comment by marcus-j-davies** [comment]
Great!

I'm glad it's all working for you.
Battery Operated ZWave devices are usually designed to stay a sleep unless they need to transmit events - which sometimes causes problems when trying to configure them. 

Your device does support setting the Wake Interval, so you can use the node to set it.
(Ensuring its a wake of course)

Manufactures usually   impose limitations on how small this number can be - so read up on its minimum value.

once set - you can (providing the battery is reported on this interval) keep an accurate value for the battery, this is what I do with my door sensors and siren.

**Comment by Folgore796** [comment]
I have only this device in zwave. 

You have made a great job for this node. Beacause, the openzwave node is very long to install and try. I have spent many time. Now is very simple. Thank'you very much.

**Comment by marcus-j-davies** [comment]
Simplicity was my goal here - So you are very welcome. Thank you
